<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>zenoh_joy_rs</name>
  <version>0.1.0</version>
  <description>Production-grade, zero-latency teleoperation controller publisher for robotics over Zenoh 1.0</description>
  <maintainer email="tatsv@users.noreply.github.com">tatsv</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>zenoh_bridge_ros2dds</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
